In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
%pprint

Pretty printing has been turned OFF

In [14]:
dir = "../mnt_processed_data/"

In [70]:
def check_simulations(freq, var, res): 
    dat = []
    files = glob.glob(dir+res+"/"+var+"_"+freq+"*5x5.nc")
    for f in files: 
        ds = xr.open_dataset(f)
        if res == "cmip": 
            v = f.split("/")[-1].split("_")[5]
        elif res == "highres_cmip":
            v = f.split("/")[-1].split("_")[4]
        m = f.split("/")[-1].split("_")[2]
        
        d = pd.DataFrame({'freq': [freq], 'var': [var], 'model': [m], 'variant': [v], 'length': [len(ds.time)], 
                          'start_date': [ds.time[0].values], 'end_date': [ds.time[-1].values]})
        dat.append(d)

    dat = pd.concat(dat)
    dat.to_csv(dir+res+"_simulation_table_"+freq+"_"+var+".csv", index = False)

    return(dat)

In [73]:
check_simulations("mon", "pr", "cmip")

,freq,var,model,variant,length,start_date,end_date
0,mon,pr,CanESM5,r8i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,ACCESS-CM2,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,ACCESS-ESM1-5,r29i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CanESM5,r19i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,FGOALS-g3,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
...,...,...,...,...,...,...,...
0,mon,pr,ACCESS-ESM1-5,r38i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CanESM5-1,r2i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,EC-Earth3,r136i1p1f1,1572,1970-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,EC-Earth3-Veg-LR,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CNRM-CM6-1,r5i1p1f2,3012,1850-01-16 12:00:00,2100-12-16 12:00:00

In [74]:
check_simulations("day", "pr", "cmip")

,freq,var,model,variant,length,start_date,end_date
0,day,pr,EC-Earth3,r136i1p1f1,47847,1970-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MRI-ESM2-0,r1i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MIROC6,r31i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,EC-Earth3-Veg,r2i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MPI-ESM1-2-LR,r7i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
...,...,...,...,...,...,...,...
0,day,pr,MIROC6,r3i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,CanESM5,r24i1p1f1,91615,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,EC-Earth3,r127i1p1f1,47847,1970-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,CESM2,r4i1p1f1,91615,1850-01-01 00:00:00,2100-12-31 00:00:00
0,day,pr,MIROC6,r20i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00

In [71]:
check_simulations("day", "pr", "highres_cmip")

,freq,var,model,variant,length,start_date,end_date
0,day,pr,HadGEM3-GC31-MM,r1i3p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,CNRM-CM6-1,r2i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,EC-Earth3P-HR,r1i1p2f1,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,CNRM-CM6-1,r3i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,CNRM-CM6-1,r1i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,EC-Earth3P-HR,r2i1p2f1,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,EC-Earth3P-HR,r3i1p2f1,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,HadGEM3-GC31-HM,r1i3p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,HadGEM3-GC31-LL,r1i2p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,HadGEM3-GC31-MM,r1i1p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,MPI-ESM1-2-HR,r1i1p1f1,36890,1950-01-01 23:56:00,2050-12-31 23:56:00
0,day,pr,CNRM-CM6-1-HR,r1i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,CNRM-CM6-1-HR,r2i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,HadGEM3-GC31-HM,r1i1p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,CMCC-CM2-HR4,r1i1p1f1,36865,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,CMCC-CM2-VHR4,r1i1p1f1,36865,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,CNRM-CM6-1-HR,r3i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,HadGEM3-GC31-LL,r1i4p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,MPI-ESM1-2-XR,r1i1p1f1,36890,1950-01-01 23:58:00,2050-12-31 23:58:00
0,day,pr,HadGEM3-GC31-LL,r1i3p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,HadGEM3-GC31-HH,r1i1p1f1,36345,1950-01-16 12:00:00,2050-12-30 12:00:00
0,day,pr,FGOALS-f3-H,r1i1p1f1,36865,1950-01-01 12:00:00,2050-12-31 12:00:00
0,day,pr,HadGEM3-GC31-HM,r1i2p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,HadGEM3-GC31-MM,r1i2p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
0,day,pr,HadGEM3-GC31-LL,r1i1p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00

In [72]:
check_simulations("mon", "pr", "highres_cmip")

,freq,var,model,variant,length,start_date,end_date
0,mon,pr,HadGEM3-GC31-LL,r1i4p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HiRAM-SIT-HR,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,EC-Earth3P-HR,r1i1p2f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,CMCC-CM2-HR4,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,EC-Earth3P-HR,r3i1p2f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,HadGEM3-GC31-LL,r1i3p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HiRAM-SIT-LR,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,EC-Earth3P-HR,r2i1p2f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,CNRM-CM6-1-HR,r1i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,HadGEM3-GC31-HM,r1i2p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,CNRM-CM6-1-HR,r3i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,CMCC-CM2-VHR4,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,CNRM-CM6-1-HR,r2i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,HadGEM3-GC31-HH,r1i1p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HadGEM3-GC31-LL,r1i1p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HadGEM3-GC31-MM,r1i2p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,MPI-ESM1-2-HR,r1i1p1f1,1212,1950-01-31 23:56:00,2050-12-31 23:56:00
0,mon,pr,CNRM-CM6-1,r1i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,CNRM-CM6-1,r2i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,CNRM-CM6-1,r3i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,HadGEM3-GC31-MM,r1i3p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HadGEM3-GC31-HM,r1i3p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,MPI-ESM1-2-XR,r1i1p1f1,1212,1950-01-31 23:58:00,2050-12-31 23:58:00
0,mon,pr,FGOALS-f3-H,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
0,mon,pr,HadGEM3-GC31-MM,r1i1p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HadGEM3-GC31-LL,r1i2p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
0,mon,pr,HadGEM3-GC31-HM,r1i1p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00

# check simulations

### regular CMIP monthly:

In [137]:
mon_table = pd.read_csv(dir+"cmip_simulation_table_mon_pr.csv")
mon_table = mon_table[(mon_table['start_date'] <= "1930-01")]

In [138]:
# remove high-res models
mon_table = mon_table[mon_table["model"] != "CNRM-CM6-1-HR"]

In [139]:
# check for missing dates:
mon_table[mon_table["length"] < 3012]

,freq,var,model,variant,length,start_date,end_date
125,mon,pr,E3SM-1-0,r2i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
137,mon,pr,GISS-E2-1-G,r4i1p5f1,2412,1850-01-16 12:00:00,2050-12-16 12:00:00
148,mon,pr,E3SM-1-0,r3i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
168,mon,pr,E3SM-1-0,r1i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
184,mon,pr,E3SM-1-0,r5i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
209,mon,pr,E3SM-1-0,r4i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
211,mon,pr,CAMS-CSM1-0,r1i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
238,mon,pr,CAMS-CSM1-0,r2i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
245,mon,pr,IITM-ESM,r1i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00

In [140]:
## number of simulations per model
mon_table.groupby("model").count()

                  freq  var  variant  length  start_date  end_date
model
ACCESS-CM2          10   10       10      10          10        10
ACCESS-ESM1-5       40   40       40      40          40        40
AWI-CM-1-1-MR        1    1        1       1           1         1
BCC-CSM2-MR          1    1        1       1           1         1
CAMS-CSM1-0          2    2        2       2           2         2
CAS-ESM2-0           2    2        2       2           2         2
CESM2                3    3        3       3           3         3
CESM2-WACCM          3    3        3       3           3         3
CMCC-CM2-SR5         1    1        1       1           1         1
CMCC-ESM2            1    1        1       1           1         1
CNRM-CM6-1           6    6        6       6           6         6
CNRM-ESM2-1          5    5        5       5           5         5
CanESM5             50   50       50      50          50        50
CanESM5-1           20   20       20      20          20        20
E3SM-1-0             5    5        5       5           5         5
E3SM-1-1-ECA         1    1        1       1           1         1
EC-Earth3            7    7        7       7           7         7
EC-Earth3-CC         1    1        1       1           1         1
EC-Earth3-Veg        9    9        9       9           9         9
EC-Earth3-Veg-LR     3    3        3       3           3         3
FGOALS-f3-L          1    1        1       1           1         1
FGOALS-g3            4    4        4       4           4         4
GFDL-CM4             1    1        1       1           1         1
GFDL-ESM4            1    1        1       1           1         1
GISS-E2-1-G         14   14       14      14          14        14
GISS-E2-2-G          5    5        5       5           5         5
HadGEM3-GC31-LL      4    4        4       4           4         4
HadGEM3-GC31-MM      4    4        4       4           4         4
IITM-ESM             1    1        1       1           1         1
INM-CM4-8            1    1        1       1           1         1
INM-CM5-0            1    1        1       1           1         1
IPSL-CM6A-LR         7    7        7       7           7         7
KACE-1-0-G           3    3        3       3           3         3
KIOST-ESM            1    1        1       1           1         1
MIROC-ES2L          10   10       10      10          10        10
MIROC6              50   50       50      50          50        50
MPI-ESM1-2-HR        2    2        2       2           2         2
MPI-ESM1-2-LR       50   50       50      50          50        50
MRI-ESM2-0           6    6        6       6           6         6
NESM3                2    2        2       2           2         2
NorESM2-MM           1    1        1       1           1         1
TaiESM1              1    1        1       1           1         1
UKESM1-0-LL          5    5        5       5           5         5

In [141]:
print("there are", len(mon_table), "monthly simulations")
print("there are", len(set(mon_table.model)), "models")

there are 346 monthly simulations
there are 43 models

In [142]:
mon_table = mon_table.sort_values("variant").reset_index()
mon_table = pd.concat([mon_table[mon_table.variant == "r1i1p1f1"], mon_table[mon_table.variant != "r1i1p1f1"]])
mon_table_onevar = mon_table.groupby("model").first().reset_index()

In [143]:
cmip_mon_vars = list(mon_table["model"]+"_"+mon_table["variant"])
cmip_mon_onevars = list(mon_table_onevar["model"]+"_"+mon_table_onevar["variant"])

### regular CMIP day:

In [150]:
day_table = pd.read_csv(dir+"cmip_simulation_table_day_pr.csv")
day_table = day_table[(day_table['start_date'] <= "1950-01")]
# remove high-res models
day_table = day_table[day_table["model"] != "CNRM-CM6-1-HR"]

In [169]:
day_table[day_table["model"] == "EC-Earth3-CC"]

,index,freq,var,model,variant,length,start_date,end_date
64,180,day,pr,EC-Earth3-CC,r1i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00

In [151]:
day_table[day_table["length"] < 90360] #90360 is number of days 1850-2100 with 360-day calendar

,freq,var,model,variant,length,start_date,end_date
305,day,pr,UKESM1-0-LL,r15i1p1f2,35640,1850-01-01 12:00:00,2099-12-30 12:00:00
310,day,pr,UKESM1-0-LL,r14i1p1f2,80640,1850-01-01 12:00:00,2099-12-30 12:00:00

In [152]:
day_table = day_table[day_table["length"] >= 90360]

In [153]:
day_table.groupby("model").count()

                  freq  var  variant  length  start_date  end_date
model
ACCESS-CM2          10   10       10      10          10        10
ACCESS-ESM1-5       40   40       40      40          40        40
BCC-CSM2-MR          1    1        1       1           1         1
CAMS-CSM1-0          1    1        1       1           1         1
CESM2                2    2        2       2           2         2
CESM2-WACCM          3    3        3       3           3         3
CMCC-CM2-SR5         1    1        1       1           1         1
CMCC-ESM2            1    1        1       1           1         1
CNRM-CM6-1           1    1        1       1           1         1
CNRM-ESM2-1          1    1        1       1           1         1
CanESM5             50   50       50      50          50        50
EC-Earth3            7    7        7       7           7         7
EC-Earth3-CC         1    1        1       1           1         1
EC-Earth3-Veg        8    8        8       8           8         8
EC-Earth3-Veg-LR     3    3        3       3           3         3
FGOALS-g3            3    3        3       3           3         3
GFDL-CM4             1    1        1       1           1         1
GFDL-ESM4            1    1        1       1           1         1
HadGEM3-GC31-LL      4    4        4       4           4         4
HadGEM3-GC31-MM      4    4        4       4           4         4
IITM-ESM             1    1        1       1           1         1
INM-CM4-8            1    1        1       1           1         1
INM-CM5-0            1    1        1       1           1         1
IPSL-CM6A-LR         7    7        7       7           7         7
KACE-1-0-G           3    3        3       3           3         3
KIOST-ESM            1    1        1       1           1         1
MIROC-ES2L          10   10       10      10          10        10
MIROC6              50   50       50      50          50        50
MPI-ESM1-2-HR        2    2        2       2           2         2
MPI-ESM1-2-LR       50   50       50      50          50        50
MRI-ESM2-0           6    6        6       6           6         6
NESM3                1    1        1       1           1         1
NorESM2-LM           1    1        1       1           1         1
NorESM2-MM           1    1        1       1           1         1
TaiESM1              1    1        1       1           1         1
UKESM1-0-LL          5    5        5       5           5         5

In [154]:
print("there are", len(day_table), "daily simulations")
print("there are", len(set(day_table.model)), "models")

there are 284 daily simulations
there are 36 models

In [155]:
day_table = day_table.sort_values("variant").reset_index()
day_table = pd.concat([day_table[day_table.variant == "r1i1p1f1"], day_table[day_table.variant != "r1i1p1f1"]])
day_table_onevar = day_table.groupby("model").first().reset_index()

In [156]:
cmip_day_vars = list(day_table["model"]+"_"+day_table["variant"])
cmip_day_onevars = list(day_table_onevar["model"]+"_"+day_table_onevar["variant"])

### HighRes mon:

In [157]:
hr_mon_table = pd.read_csv(dir+"highres_cmip_simulation_table_mon_pr.csv")
## remove low-res models
hr_mon_table = hr_mon_table.loc[~hr_mon_table.model.isin(["CMCC-CM2-HR4", "CNRM-CM6-1", "HadGEM3-GC31-LL", "HadGEM3-GC31-MM", "MPI-ESM1-2-HR"])]
hr_mon_table

,freq,var,model,variant,length,start_date,end_date
1,mon,pr,HiRAM-SIT-HR,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
2,mon,pr,EC-Earth3P-HR,r1i1p2f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
4,mon,pr,EC-Earth3P-HR,r3i1p2f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
6,mon,pr,HiRAM-SIT-LR,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
7,mon,pr,EC-Earth3P-HR,r2i1p2f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
8,mon,pr,CNRM-CM6-1-HR,r1i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
9,mon,pr,HadGEM3-GC31-HM,r1i2p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
10,mon,pr,CNRM-CM6-1-HR,r3i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
11,mon,pr,CMCC-CM2-VHR4,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
12,mon,pr,CNRM-CM6-1-HR,r2i1p1f2,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
13,mon,pr,HadGEM3-GC31-HH,r1i1p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
21,mon,pr,HadGEM3-GC31-HM,r1i3p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00
22,mon,pr,MPI-ESM1-2-XR,r1i1p1f1,1212,1950-01-31 23:58:00,2050-12-31 23:58:00
23,mon,pr,FGOALS-f3-H,r1i1p1f1,1212,1950-01-16 12:00:00,2050-12-16 12:00:00
26,mon,pr,HadGEM3-GC31-HM,r1i1p1f1,1212,1950-01-16 00:00:00,2050-12-16 00:00:00

In [158]:
print("there are", len(hr_mon_table), "HR monthly simulations")
print("there are", len(set(hr_mon_table.model)), "HR models")

there are 15 HR monthly simulations
there are 9 HR models

In [159]:
hr_mon_vars = list(hr_mon_table["model"]+"_"+hr_mon_table["variant"])

### HighRes day:

In [160]:
hr_day_table = pd.read_csv(dir+"highres_cmip_simulation_table_day_pr.csv")
## remove low-res models
hr_day_table = hr_day_table.loc[~hr_day_table.model.isin(["CMCC-CM2-HR4", "CNRM-CM6-1", "HadGEM3-GC31-LL", "HadGEM3-GC31-MM", "MPI-ESM1-2-HR"])]
hr_day_table

,freq,var,model,variant,length,start_date,end_date
2,day,pr,EC-Earth3P-HR,r1i1p2f1,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
5,day,pr,EC-Earth3P-HR,r2i1p2f1,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
6,day,pr,EC-Earth3P-HR,r3i1p2f1,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
7,day,pr,HadGEM3-GC31-HM,r1i3p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
11,day,pr,CNRM-CM6-1-HR,r1i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
12,day,pr,CNRM-CM6-1-HR,r2i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
13,day,pr,HadGEM3-GC31-HM,r1i1p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00
15,day,pr,CMCC-CM2-VHR4,r1i1p1f1,36865,1950-01-01 12:00:00,2050-12-31 12:00:00
16,day,pr,CNRM-CM6-1-HR,r3i1p1f2,36890,1950-01-01 12:00:00,2050-12-31 12:00:00
18,day,pr,MPI-ESM1-2-XR,r1i1p1f1,36890,1950-01-01 23:58:00,2050-12-31 23:58:00
20,day,pr,HadGEM3-GC31-HH,r1i1p1f1,36345,1950-01-16 12:00:00,2050-12-30 12:00:00
21,day,pr,FGOALS-f3-H,r1i1p1f1,36865,1950-01-01 12:00:00,2050-12-31 12:00:00
22,day,pr,HadGEM3-GC31-HM,r1i2p1f1,36360,1950-01-01 12:00:00,2050-12-30 12:00:00

In [161]:
print("there are", len(hr_day_table), "HR daily simulations")
print("there are", len(set(hr_day_table.model)), "HR models")

there are 13 HR daily simulations
there are 7 HR models

In [162]:
hr_day_vars = list(hr_day_table["model"]+"_"+hr_day_table["variant"])

### Save list of model variants

In [123]:
import json

In [163]:
model_var_dict = {"cmip_mon": cmip_mon_vars, 
"cmip_mon_onevar": cmip_mon_onevars,
"cmip_day": cmip_day_vars, 
"cmip_day_onevar": cmip_day_onevars,    
"highres_mon": hr_mon_vars, 
                 "highres_day": hr_day_vars}

In [168]:
json.dump(model_var_dict, open(dir+"model_var_dict.json", 'w' ))