In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
%pprint

Pretty printing has been turned OFF

In [4]:
## use regridded cmip data as check
cmip_dir = "/davenport-scratch/fvdav22/projects/extreme-precip-trends/processed_data/CMIP6/"

In [5]:
def check_simulations(freq, var): 
    dat = []
    files = glob.glob(cmip_dir+var+"_"+freq+"*5x5.nc")
    for f in files: 
        ds = xr.open_dataset(f)
        m = f.split("/")[-1].split("_")[2]
        v = f.split("/")[-1].split("_")[5]
        d = pd.DataFrame({'freq': [freq], 'var': [var], 'model': [m], 'variant': [v], 'length': [len(ds.time)], 
                          'start_date': [ds.time[0].values], 'end_date': [ds.time[-1].values]})
        dat.append(d)

    dat = pd.concat(dat)
    dat.to_csv("../processed_data/simulation_table_"+freq+"_"+var+".csv", index = False)

    return(dat)

In [6]:
check_simulations("mon", "pr")

,freq,var,model,variant,length,start_date,end_date
0,mon,pr,CanESM5,r8i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,ACCESS-CM2,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,ACCESS-ESM1-5,r29i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CanESM5,r19i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,FGOALS-g3,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
...,...,...,...,...,...,...,...
0,mon,pr,ACCESS-ESM1-5,r38i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CanESM5-1,r2i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,EC-Earth3,r136i1p1f1,1572,1970-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,EC-Earth3-Veg-LR,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CNRM-CM6-1,r5i1p1f2,3012,1850-01-16 12:00:00,2100-12-16 12:00:00

In [7]:
check_simulations("day", "pr")

,freq,var,model,variant,length,start_date,end_date
0,day,pr,EC-Earth3,r136i1p1f1,47847,1970-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MRI-ESM2-0,r1i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MIROC6,r31i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,EC-Earth3-Veg,r2i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MPI-ESM1-2-LR,r7i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
...,...,...,...,...,...,...,...
0,day,pr,MIROC6,r3i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,CanESM5,r24i1p1f1,91615,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,EC-Earth3,r127i1p1f1,47847,1970-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,CESM2,r4i1p1f1,91615,1850-01-01 00:00:00,2100-12-31 00:00:00
0,day,pr,MIROC6,r20i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00

In [9]:
sim_table = pd.read_csv("../processed_data/simulation_table_day_pr.csv")
sim_table = sim_table[(sim_table['start_date'] <= "1930-01") & (sim_table['end_date'] >= "2024-12")]
sim_table_onevar = sim_table.sort_values("variant").groupby("model").first().reset_index()
onevar_model_keys = list(sim_table_onevar["model"]+"_"+sim_table_onevar["variant"])

In [10]:
sim_table

,freq,var,model,variant,length,start_date,end_date
1,day,pr,MRI-ESM2-0,r1i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
2,day,pr,MIROC6,r31i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
3,day,pr,EC-Earth3-Veg,r2i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
4,day,pr,MPI-ESM1-2-LR,r7i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
5,day,pr,ACCESS-ESM1-5,r16i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
...,...,...,...,...,...,...,...
323,day,pr,EC-Earth3,r13i1p1f1,91674,1850-01-01 12:00:00,2100-12-31 12:00:00
324,day,pr,MIROC6,r3i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
325,day,pr,CanESM5,r24i1p1f1,91615,1850-01-01 12:00:00,2100-12-31 12:00:00
327,day,pr,CESM2,r4i1p1f1,91615,1850-01-01 00:00:00,2100-12-31 00:00:00
328,day,pr,MIROC6,r20i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00

In [19]:
day_table = pd.read_csv("../processed_data/simulation_table_day_pr.csv")
day_table[(sim_table['start_date'] <= "1930-01") & (sim_table['length'] < 91600)]

,freq,var,model,variant,length,start_date,end_date
8,day,pr,HadGEM3-GC31-LL,r3i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
15,day,pr,HadGEM3-GC31-LL,r2i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
24,day,pr,HadGEM3-GC31-MM,r4i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
39,day,pr,HadGEM3-GC31-LL,r1i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
51,day,pr,HadGEM3-GC31-LL,r4i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
58,day,pr,HadGEM3-GC31-MM,r1i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
67,day,pr,HadGEM3-GC31-MM,r3i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
89,day,pr,HadGEM3-GC31-MM,r2i1p1f3,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
150,day,pr,EC-Earth3-Veg,r10i1p1f1,91310,1850-01-01 12:00:00,2100-12-31 12:00:00
195,day,pr,CAMS-CSM1-0,r2i1p1f1,91311,1850-01-01 12:00:00,2099-12-31 12:00:00
235,day,pr,UKESM1-0-LL,r8i1p1f2,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
266,day,pr,UKESM1-0-LL,r1i1p1f2,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
277,day,pr,UKESM1-0-LL,r3i1p1f2,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
280,day,pr,UKESM1-0-LL,r2i1p1f2,90360,1850-01-01 12:00:00,2100-12-30 12:00:00
296,day,pr,UKESM1-0-LL,r15i1p1f2,35640,1850-01-01 12:00:00,2099-12-30 12:00:00
301,day,pr,UKESM1-0-LL,r14i1p1f2,80640,1850-01-01 12:00:00,2099-12-30 12:00:00
315,day,pr,UKESM1-0-LL,r4i1p1f2,90360,1850-01-01 12:00:00,2100-12-30 12:00:00

In [21]:
sim_table = pd.read_csv("../processed_data/simulation_table_mon_pr.csv")
sim_table[(sim_table['start_date'] <= "1930-01") & (sim_table['length'] < 3012)]

,freq,var,model,variant,length,start_date,end_date
125,mon,pr,E3SM-1-0,r2i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
137,mon,pr,GISS-E2-1-G,r4i1p5f1,2412,1850-01-16 12:00:00,2050-12-16 12:00:00
148,mon,pr,E3SM-1-0,r3i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
168,mon,pr,E3SM-1-0,r1i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
184,mon,pr,E3SM-1-0,r5i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00
211,mon,pr,CAMS-CSM1-0,r1i1p1f1,3000,1850-01-16 12:00:00,2099-12-16 12:00:00